### ISSUE TITLE
[bug]: Android back should close drawers and not close the app

### ISSUE THREAD

**Issue by cokes518** [helium/wallet-issues-tracker#18]
### bug

reported by a user in discord:

Is it possible we could amend the back button behaviour on Android to close any 'drawers' that are open rather than close the app entirely? Quite annoying as that's not the typical behaviour for a back button action, it's to dismiss any prompts, menus and drawers etc. Would be much appreciated!

### Phone Type

Android

### Network Type

Mainnet

**Comment by gexeh** [comment]
I'm the guy who raised the issue, it's not a major problem just a minor UI workflow change.

What I found is when you tap on a 'Mining Reward' in the 'My Transactions' list to show more information about a specific reward, it opens the details in a drawer type UI element at the bottom of the screen, the issue I've found is that you would expect the native Android back button action to close any visible drawer and once theres none visible the next back action would close the app, but instead it closes the app right away when you want to return to the list.

Hope this helps, I can't attach a screenshot due to the security settings within the app.
